feat: rank-dto
ft-minigame/mini-backend pull request #23
Opened 2023-05-29 05:28 UTC by aeyongdodam

findAll과 findOne 작성하였습니다~
기존에 uuid를 game 엔티티에서 가져오게 작성하였는데, 유저 엔티티에서 uuid 가져오게 수정했어요

2023-05-29 07:18 UTC, aeyongdodam commented
return해주는 것이라 dto보다 response가 더 적합할 것 같아서 dto에서 response로 이름을 바꾸고 
response는 인터페이스, dto는 클래스여야 해서 그에 맞춰서 바꿨습니다

2023-05-29 07:22 UTC, jooocy approved these changes
lgtm

2023-06-03 11:12 UTC, jooocy requested changes
리뷰남깁니다.

2023-06-03 11:12 UTC, jooocy commented on src/v1/rank/controllers/rank.controller.ts
> +  async findOneBy(@Param('id') intraId: string): Promise<FindOneRankResponse> {
```suggestion
  async findOneBy(@Param('intraId') intraId: string): Promise<FindOneRankResponse> {
```

2023-06-03 11:12 UTC, jooocy commented on src/v1/rank/domain/repositories/rank.repository.ts
> +    const { createdAt, score, nickname } = await this.createQueryBuilder('game')
잘했어요. 근데 찾는걸 실패하면 어떻게 될까요? 키워드는 try catch와 throw입니다.

2023-06-03 11:12 UTC, jooocy requested changes
리뷰남깁니다.

2023-06-04 09:58 UTC, merged