build: game repository
ft-minigame/mini-backend pull request #24
Opened 2023-05-29 07:05 UTC by saltwoodYJ

game 컨트롤러, 서비스, 레포지토리, 모듈 구현하고
create dto, update dto 만들엇습니당
확인해주세요

2023-06-03 11:08 UTC, jooocy requested changes
수정이 필요한 부분이 있어요

2023-06-03 11:08 UTC, jooocy commented on src/v1/game/controllers/game.controller.ts
> +  @Post('start')
저희 api create이에여 수정해주세요
https://www.notion.so/Workflow-14b0071301694ce79c983c38ee3a7b29

2023-06-03 11:08 UTC, jooocy commented on src/v1/game/controllers/game.controller.ts
> +  @Post('start')
저희 리턴에대한 api를 정하지 않았어요. 우선은 이대로 가지만 추후에 변경이 필요합니다.

2023-06-03 11:08 UTC, jooocy commented on src/v1/game/dto/create-game.dto.ts
dto의 목적에 맞지 않습니다. dto는 일반적으로 데이터의 validate으로 쓰입니다.  
제가 코드작성 했는지는 기억이 안나는데 찾아보시고 없으면 검색해서 수정해주세요

2023-06-03 11:08 UTC, jooocy commented on src/v1/game/dto/update-game.dto.ts
> +  user: User;
저희는 직접적으로 user를 참조하지 않습니다. 직접참조 간접참조 검색해보면 알수있을거에요

2023-06-03 11:08 UTC, jooocy commented on src/v1/game/domain/repositories/game.repository.ts
> +    super(Game, gameSources.createEntityManager());
혹시 이거를 해주는 이유는 뭔가요? 없으면 동작을 안하나요?

2023-06-03 11:08 UTC, jooocy commented on src/v1/game/domain/repositories/game.repository.ts
> +  }
잘 구현했어요. 근데 create이 실패하게 되면 어떻게 될까요? 키워드는 try catch 와 throw 입니다.

2023-06-03 11:08 UTC, jooocy requested changes
수정이 필요한 부분이 있어요

2023-06-03 11:08 UTC, jooocy reviewed
그리고 build가 아니고 feat으로 해야합니다.

2023-06-11 10:50 UTC, saltwoodYJ commented on src/v1/game/dto/create-game.dto.ts
> +  playTime: Date = new Date();
Date타입은 null설정이 안되는것같아서 일단 new Date()로 생성 날짜 넣어두긴 했습니다

2023-06-11 10:50 UTC, saltwoodYJ commented on src/v1/game/dto/update-game.dto.ts
> +  updateTime: Date = new Date();
생각해보니 얘는 애초에 entity에서 updateDateColumn 설정이 되어잇어서 불필요한 아이인거 같네요 수정후 다시 커밋하겠습니다

2023-06-11 10:50 UTC, saltwoodYJ commented on src/v1/game/controllers/game.controller.ts
> +  @Post('start')
patch 없애고 create로 수정했습니당

2023-06-11 10:52 UTC, saltwoodYJ commented on src/v1/game/dto/create-game.dto.ts
dto 수정하긴했는데 playTime에 @IsDate()넣으니까 postman에서 값을 아예 못받아먹길래 일단 빼뒀어요

2023-06-11 10:52 UTC, saltwoodYJ commented on src/v1/game/dto/update-game.dto.ts
> +  user: User;
얘도 intraId로 수정했슴당

2023-06-11 10:53 UTC, saltwoodYJ commented on src/v1/game/domain/repositories/game.repository.ts
> +  }
throw Error 사용하긴했는데 잘쓴건지는 모르겠어요 확인부탁드립니다

2023-06-11 11:00 UTC, saltwoodYJ commented on src/v1/game/domain/repositories/game.repository.ts
> +    super(Game, gameSources.createEntityManager());
없으면 레포지토리 메소드 사용이 불가능하지않나요..??

2023-06-11 11:45 UTC, saltwoodYJ commented on src/v1/game/domain/repositories/game.repository.ts
> +    try {
thorw만 쓰던거 try catch문으로 변경해보았어요

2023-06-11 11:51 UTC, aeyongdodam approved these changes

2023-06-11 11:51 UTC, aeyongdodam commented on src/v1/game/domain/repositories/game.repository.ts
> +    try {
lgtm~~

2023-06-11 12:03 UTC, merged