Build/feat enf config
ft-minigame/mini-backend pull request #3
Opened 2023-04-18 12:10 UTC by saltwoodYJ

module에서 db연결 config로 설정하고
.dev.env는 gitignore로 설정하고 푸쉬했어요
이렇게하는게 맞는지 모르겠어요 확인해주세요

2023-04-19 14:06 UTC, jooocy commented
우선 리뷰어에 저를 넣어주세요

2023-04-19 14:07 UTC, jooocy commented
커밋 메세지는 영어로 해주세요

2023-04-19 14:09 UTC, jooocy commented
7b3c233 커밋메세지는 feat: initalize typeORM 같이 하는것이 적당합니다. fix는 동작에 에러가 있는것을 고칠때 사용합니다.

2023-04-19 14:15 UTC, jooocy requested changes
nest config를 사용한것 같은데 install해서 사용한게 맞나요?(install부분의 pr이 없어서 질문합니다.)

확인하고 일요일까지 작업해서 pr올리면 좋겠습니다. 
이번작업시 commit을 잘 쪼개봅시다.!

2023-04-19 14:15 UTC, jooocy commented on src/app.module.ts
cat관련하여 사용하지 않는것들 지워주세요

2023-04-19 14:15 UTC, jooocy commented on src/app.module.ts
> +  }),
잘 해준것 같습니다. 실제동작하는걸 확인한걸로 기억하고 있는데 맞을까요?

조금 욕심을 내보자면 return으로 받으니까 따로 파일을 만들어서 return받도록 바꿔주면 좋을것 같습니다.

2023-04-19 14:18 UTC, jooocy commented
피알 제목에 오타 있습니다. 수정해주세요
피알을 XXX: aaa 이런양식으로 합시다.

2023-04-24 13:44 UTC, saltwoodYJ commented on src/app.module.ts
지우고 커밋 남겼습니다!

2023-04-24 13:45 UTC, saltwoodYJ reviewed
module install 부분 두개 @nestjs/typeorm, @nestjs/config 커밋 남겼고
cat도 삭제완료했어요!

2023-05-01 01:18 UTC, jooocy approved these changes
lgtm

2023-05-01 01:55 UTC, merged